### PR TITLE
Add pop_X_handler and clear_X_handlers methods.

### PR DESCRIPTION
**Pull request by rhofour**
I decided to leave the add_X_handler methods as-is since push_X_handler doesn't match up to what Python lists use.

This addresses #7

### CODE REVIEW

**Review by qtux — COMMENTED** [review]
Could you please use list.clear() instead of assigning an empty array? E.g. self.emg_handlers.clear() instead of self.emg_handlers = [].

**Comment by qtux** [comment]
Sounds good to me. What do you think about renaming the add_X_handler into append_X_handler for better matching Python lists?

**Comment by rhofour** [comment]
I must have been looking at old docs. I looked for something like .clear() and didn't see it. Done.

I think the add_ functions are already clear enough (and long enough). append_... might be a slightly better name, but I don't think it's worth breaking backwards compatibility over. If you prefer it though I could easily do that too.

**Review by qtux — APPROVED** [review]
Thanks :)

**Comment by qtux** [comment]
Let's stay with add_... Thank you for your contribution :).

**Pull request merged**
